### ISSUE TITLE
[ERROR] Installing package with composer 

### ISSUE THREAD

**Issue by nosent79** [nanoninja/docker-nginx-php-mysql#10]
HI @nanoninja,

At first, I'm sorry that not good at English well.

I tried to install composer. But I faced with Error.

What can I do?

jerryui-MacBook-Pro:docker-nginx-php-mysql jerry$ sudo docker run --rm -v /Users/jerry/Dev/docker-nginx-php-mysql/web/app:/app composer require symfony/yaml
Password:
Using version ^4.0 for symfony/yaml
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install symfony/yaml v4.0.1
    - Conclusion: don't install symfony/yaml v4.0.0
    - Conclusion: don't install symfony/yaml v4.0.0-RC2
    - Conclusion: don't install symfony/yaml v4.0.0-RC1
    - Conclusion: don't install symfony/yaml v4.0.0-BETA4
    - Conclusion: don't install symfony/yaml v4.0.0-BETA3
    - Conclusion: don't install symfony/yaml v4.0.0-BETA2
    - Installation request for apigen/apigen dev-master -> satisfiable by apigen/apigen[dev-master].
    - Conclusion: don't install symfony/yaml v4.0.0-BETA1
    - Conclusion: don't install symfony/yaml 4.1.x-dev
    - apigen/apigen dev-master requires symfony/yaml ^3.3 -> satisfiable by symfony/yaml[3.3.x-dev, 3.4.x-dev].
    - Can only install one of: symfony/yaml[4.0.x-dev, 3.3.x-dev].
    - Can only install one of: symfony/yaml[4.0.x-dev, 3.4.x-dev].
    - Installation request for symfony/yaml ^4.0 -> satisfiable by symfony/yaml[4.0.x-dev, 4.1.x-dev, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by nanoninja** [comment]
Hello @nosent79,

the command in the documentation is a basic example to be able to install its dependencies at its convenience.

In our case, a number of dependencies are already installed by default and conflict with the latest version of "yaml".

If possible, you should use version 3.4 to install it without conflict or adapt your file to suit your needs.

composer.json
```json
"require": {
    "symfony/yaml": "3.*"
},
```

Vincent.
