### ISSUE TITLE
How to update the mysql root password 

### ISSUE THREAD

**Issue by furqank786** [nanoninja/docker-nginx-php-mysql#14]
@nanoninja 

I have updated the root password from the main .env file and after update password executed following commands.
1. docker-compose down -v
2. docker-compose up -d 

But still phpmyadmin accepting the old password "root".

Please help if I am missing some steps. Thank you.

**Comment by furqank786** [comment]
@nanoninja  @letvinz 

Please help me to change the MySQL root password.
Thanks

**Comment by zanematthew** [comment]
Can you not change it via the `.env` file?

**Comment by furqank786** [comment]
@zanematthew

Yes I was not able to change through the `.env` file. Still not able to find a way to update the root/test password. 
Please help me. Thanks.

**Comment by toonitw** [comment]
@furqank786 
Try to delete `./data/db/mysql`.
