### ISSUE TITLE
Add PHPMD Support

### ISSUE THREAD

**Issue by zanematthew** [nanoninja/docker-nginx-php-mysql#22]
This can be a controversial request, since _I know_ that some (most) PHP developers (still) love to;

1. Bloat their code with a ton of nested foreach if/elseif/elseif/else foreach if/else statements
1. Use underscores in method names
1. Debate on the bracket issue

Personally I use PHPMD and do like (enjoy) it.

I've added support for this on my local branch, but have not submitted a pull request. Figured, I'd ask, and open a dialog first.

Steps to add support;

1. Update the `Makefile` with; (note, this will scan _all_ your files in `app/src`)
```
phpmd:
	@docker-compose exec -T php \
		./app/vendor/bin/phpmd \
		app/src/ \
		text \
		cleancode,codesize,controversial,design,naming,unusedcode
```

2. Update composer with;

```
"phpmd/phpmd" : "@stable"
```

3. Run the composer update.

4. Use it with `make phpmd`.

**Comment by nanoninja** [comment]
Hi @zanematthew,

Sorry for my late, I have a lot of work right now.

I will look at your proposals and we will discuss them very soon if you wish.

**Comment by zanematthew** [comment]
@nanoninja no problem, understood. I'm currently using this as a base on a personal project and its going well.

**Comment by nanoninja** [comment]
Hi @zanematthew,

Thanks for your feedback.

I thought about it too and then I told myself that the choice belonged to the users. Also, I did not want the installation to be too long if I added more outbuildings.

I think that one can make an attempt at this and that doing clean code is more important than my previous considerations.

It is relevant to add phpmd to the project.
