### ISSUE TITLE
phpmyadmin doesn't work with latest mysql

### ISSUE THREAD

**Issue by max-websecret** [nanoninja/docker-nginx-php-mysql#26]
MySQL was recently updated and phpmyadmin doesn't work with it.
Please, update phpmyadmin or set mysql version to 5.7 in docker-compose.yml.
Thanks!

**Comment by nanoninja** [comment]
Hello @max-websecret,

Thank you for warning me. An update was made to solve the problem. It is now possible to change the version of MySQL from the environment variables.

[https://github.com/nanoninja/docker-nginx-php-mysql/releases/tag/v1.5.1](https://github.com/nanoninja/docker-nginx-php-mysql/releases/tag/v1.5.1)
