### ISSUE TITLE
New library 

### ISSUE THREAD

**Issue by erebolledo** [nanoninja/docker-nginx-php-mysql#4]
Hi, I am trying to get the library SOAP into php, can you help me to do that? Thanks in advance

**Comment by nanoninja** [comment]
Hello @erebolledo,

SOAP is an extension of PHP.

It is not available in the image contains [PHP-FPM](https://hub.docker.com/r/nanoninja/php-fpm/). I'll check if I can add it.

**Comment by nanoninja** [comment]
@erebolledo SOAP has been installed. [Take a look](https://hub.docker.com/r/nanoninja/php-fpm/). 

Upgrade your image : 

`sudo docker pull nanoninja/php-fpm`

Vincent.

**Comment by erebolledo** [comment]
Thanks a lot nano, you are the best!!!
