### ISSUE TITLE
Can't login in phpmyadmin

### ISSUE THREAD

**Issue by lucaingold** [nanoninja/docker-nginx-php-mysql#7]
Firstly, thank you for the great work!
After start all the containers, phpmyadmin is reachable without problem.
But it is not possible to login. I can click on login, but something with the credentials (dev, dev) or the configuration on my site must be wrong. I used the repository out of the box, no changes. Ports on the server are open. Do you know, what the missing point is?

**Comment by nanoninja** [comment]
Hi,

Thank you for supporting this project. I did a test and I do not have this problem. Have you looked at the logs to be sure there is not a hidden problem?

`docker-compose logs -f`

**Comment by lucaingold** [comment]
Thank you. It was my fault, after clean chrome browsing data it worked...
Is there also an possibility to configure SSL for MySQL like in nginx? When i run "SHOW VARIABLES LIKE '%ssl%';" in mysql there is already ssl-keys. But has it a connection with the generated keys from the nginx-configuration? Thank you!

**Comment by nanoninja** [comment]
@lucaingold You're welcome.

For MySQL and SSL this is something that one can consider in the future. I also thought about phpmyadmin. I work there when I have time.
